CREATE DATABASE IF NOT EXISTS posts;
USE posts;
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(255) NOT NULL,
  senha VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS postagens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  conteudo TEXT NOT NULL,
  curtidas INT DEFAULT 0,
  data_postagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
select * from postagens